### ISSUE TITLE
Enable past broadcasts

### ISSUE THREAD

**Issue by dbousamra** [ocharles/zero-to-quake-3#1]
Hi.

I wasn't able to catch the live stream. Are you able to enable past broadcasts so I can watch past sessions?

**Comment by ocharles** [comment]
Should already be setup. The very first broadcast is unfortunately lost for ever. Today's should be on my twitch page though. I will archive to YouTube too.

**Comment by ocharles** [comment]
Let me know if they aren't working and I'll look into this more.

**Comment by dbousamra** [comment]
Appears to work. Thanks!
